---
apiVersion: v2
appVersion: latest
description: Babybuddy
name: babybuddy
version: 0.1.0
kubeVersion: ">=1.16.0-0"
keywords: []
home: https://github.com/brettinternet/charts/tree/master/charts/babybuddy
icon: https://raw.githubusercontent.com/babybuddy/babybuddy/master/babybuddy/static_src/logo/icon.png
sources:
  - https://github.com/brettinternet/charts/tree/master/charts/babybuddy
  - https://hub.docker.com/r/linuxserver/babybuddy
  - https://github.com/babybuddy/babybuddy
maintainers:
  - name: brett
dependencies:
  - name: common
    version: 0.1.0
    repository: https://bjw-s.github.io/helm-charts/
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Initial version
