# Extends https://github.com/bjw-s/helm-charts/blob/13c511dc13e1f31c1ccfd81f67aafd369c86e1a0/charts/library/common/values.yaml
---
image:
  repository: linuxserver/babybuddy
  tag: latest
  pullPolicy: IfNotPresent

env:
  TZ: UTC
  # CSRF_TRUSTED_ORIGINS: "http://192.168.1.100:8000,https://baby.example.com"

service:
  main:
    ports:
      http:
        port: 8000

persistence:
  config:
    enabled: false
    mountPath: /config

ingress:
  main:
    enabled: false
