# Extends https://github.com/bjw-s/helm-charts/blob/13c511dc13e1f31c1ccfd81f67aafd369c86e1a0/charts/library/common/values.yaml
---
image:
  repository: adguard/adguardhome
  tag: latest
  pullPolicy: IfNotPresent

env:
  TZ: UTC

args:
  - "--config"
  - "/opt/adguardhome/conf/AdGuardHome.yaml"
  - "--work-dir"
  - "/opt/adguardhome/work"
  - "--no-check-update"

service:
  main:
    primary: true
    ports:
      http:
        port: 3000
  dns-tcp:
    enabled: true
    type: NodePort
    ports:
      dns-tcp:
        enabled: true
        port: 53
        protocol: TCP
        targetPort: 53
    externalTrafficPolicy: Local
  dns-udp:
    enabled: true
    type: NodePort
    ports:
      dns-udp:
        enabled: true
        port: 53
        protocol: UDP
        targetPort: 53
    externalTrafficPolicy: Local

persistence:
  config:
    enabled: true
    mountPath: /opt/adguardhome/conf
  data:
    enabled: false
    mountPath: /opt/adguardhome/work

ingress:
  main:
    enabled: false
