# Extends https://github.com/bjw-s/helm-charts/blob/13c511dc13e1f31c1ccfd81f67aafd369c86e1a0/charts/library/common/values.yaml
---
image:
  repository: linuxserver/dokuwiki
  tag: latest
  pullPolicy: IfNotPresent

# See https://docs.kanboard.org/en/latest/admin_guide/docker.html#environment-variables
# and application docs https://docs.kanboard.org/en/latest/admin_guide/config_file.html
env:
  TZ: UTC
  # PUID:
  # PGID:

service:
  main:
    ports:
      http:
        port: 80

persistence:
  data:
    enabled: false
    mountPath: /config

ingress:
  main:
    enabled: false
