---
apiVersion: v2
appVersion: latest
description: Miniflux RSS reader
name: miniflux
version: 0.1.0
kubeVersion: ">=1.16.0-0"
keywords: []
home: https://github.com/brettinternet/charts/tree/main/charts/miniflux
sources:
  - https://github.com/brettinternet/charts/tree/main/charts/miniflux
  - https://hub.docker.com/r/miniflux/miniflux
maintainers:
  - name: brett
dependencies:
  - name: common
    version: 0.1.0
    repository: https://bjw-s.github.io/helm-charts/
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Initial version
