# Extends https://github.com/bjw-s/helm-charts/blob/13c511dc13e1f31c1ccfd81f67aafd369c86e1a0/charts/library/common/values.yaml
---
image:
  repository: registry.gitlab.com/arm-research/smarter/smarter-device-manager
  # chart.appVersion
  tag:
  pullPolicy: IfNotPresent

# See https://gitlab.com/arm-research/smarter/smarter-device-manager for configuration examples
config: |
  - devicematch: ^ttyUSB.*$
    nummaxdevices: 1

# When using hostNetwork make sure you set dnsPolicy to `ClusterFirstWithHostNet`
hostNetwork: false
# Defaults to "ClusterFirst" if hostNetwork is false and "ClusterFirstWithHostNet" if hostNetwork is true.
dnsPolicy:  # ClusterFirstWithHostNet

termination:
  # Configure the path at which the file to which the main container's termination message will be written.
  # Overrides the default of `/dev/termination-log` to allow read-only `persistence.devfs` at `/dev`.
  # https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#lifecycle-1
  messagePath: /var/log/termination-log

  # Indicate how the main container's termination message should be populated.
  # Valid options are `File` and `FallbackToLogsOnError`.
  # smarter-device-manager does not support a termination-log, so use the container's log.
  # https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#lifecycle-1
  messagePolicy: FallbackToLogsOnError

# Configure persistence settings for the chart under this key.
persistence:
  devfs:
    enabled: true
    type: hostPath
    hostPath: /dev
    readOnly: true
  sysfs:
    enabled: true
    type: hostPath
    hostPath: /sys
    readOnly: true
  kubeletsockets:
    enabled: true
    type: hostPath
    hostPath: "/var/lib/kubelet/device-plugins"

# Custom priority class for different treatment by the scheduler
# Setting this is not necessary, but it is recommended.
# https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/
priorityClassName: system-node-critical

# Configure the securityContext for this pod
# https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
# https://gitlab.com/arm-research/smarter/smarter-device-manager/-/blob/master/smarter-device-management-pod-k3s.yaml#L7-10
securityContext:
  capabilities:
    drop:
      - ALL
  allowPrivilegeEscalation: false
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000
